language: ruby
sudo: required
rvm:
 - 2.2
env: Ubuntu=15.04
os: linux

matrix:
  fast_finish: true
  include:
    - env: OSX=10.11
      os: osx
      osx_image: xcode7.3
      rvm: system
      sudo: required

before_install:
  - ./.ci/before_install.sh

install:
  - ./.ci/install.sh

script:
  - ./.ci/test.sh
