language: ruby

matrix:
  fast_finish: true
  include:
    - env: Ubuntu=14.04
      os: linux
      dist: trusty
      sudo: required

    - env: OSX=10.11
      os: osx
      osx_image: xcode7.3
      rvm: system

before_install:
  - ./.ci/before_install.sh

install:
  - ./.ci/install.sh

script:
  - ./.ci/test.sh

git:
    depth: 3